## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -p reportportal up -d --force-recreate'
## to start all containers in daemon mode
## Where:
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2'

## Create separate volume for Redis and MongoDB data
## See https://docs.docker.com/compose/compose-file/#/volume-configuration-reference
volumes:
  reportportal-data:
    # external: true

services:
  redis:
    image: redis:3.2
    ## Uncomment if needed
    # ports:
    #   - "6379:6379"
    volumes:
      - reportportal-data:/data
    restart: always

  mongodb:
    image: mongo:3.4
    ## Uncomment if needed
    # ports:
    #     - "27017:27017"
    volumes:
      - reportportal-data:/data/db
    restart: always
    ## Consider disabling smallfiles for production usage
    command: --smallfiles

  registry:
    image: reportportal/service-registry:3.0.0
    ports:
       - "8761:8761"
    restart: always

  uat:
    image: reportportal/service-authorization:3.0.0
    # ports:
    #   - "9999:8080"
    depends_on:
      - redis
      - mongodb
      - registry
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
    # - RP_MONGO_HOST=XXX
    # - RP_MONGO_PORT=27017
    # - RP_MONGO_DB_NAME=reportportal
    # - RP_MONGO_USER=XXX
    # - RP_MONGO_PASSWORD=XXX
    restart: always

  gateway:
    image: reportportal/service-gateway:3.0.0
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - redis
      - mongodb
      - registry
    environment:
      - RP_PROFILES=docker
    restart: always

  api:
    image: reportportal/service-api:3.0.0
    depends_on:
      - redis
      - mongodb
      - registry
    environment:
      - RP_PROFILES=docker
    # - RP_MONGO_HOST=XXX
    # - RP_MONGO_PORT=27017
    # - RP_MONGO_DB_NAME=reportportal
    # - RP_MONGO_USER=XXX
    # - RP_MONGO_PASSWORD=XXX
    restart: always

  ui:
    image: reportportal/service-ui:3.0.2
    depends_on:
      - registry
    environment:
      - RP_PROFILES=docker
    restart: always

  jira:
    image: reportportal/service-jira:3.0.0
    depends_on:
      - registry
    environment:
      - RP_PROFILES=docker
    # - RP_MONGO_HOST=XXX
    # - RP_MONGO_PORT=27017
    # - RP_MONGO_DB_NAME=reportportal
    # - RP_MONGO_USER=XXX
    # - RP_MONGO_PASSWORD=XXX
    restart: always

  rally:
    image: reportportal/service-rally:3.0.0
    depends_on:
      - registry
    environment:
      - RP_PROFILES=docker
    # - RP_MONGO_HOST=XXX
    # - RP_MONGO_PORT=27017
    # - RP_MONGO_DB_NAME=reportportal
    # - RP_MONGO_USER=XXX
    # - RP_MONGO_PASSWORD=XXX
    restart: always
